// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RR.Infrastructure.Persistence;

#nullable disable

namespace RR.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513140956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RR.Core.Domain.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("area");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_name");

                    b.Property<string>("AuthorProfileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("author_profile_url");

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("available_from");

                    b.Property<DateOnly?>("AvailableUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("available_until");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bedrooms");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence_score");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_info");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<bool?>("HasHotWater")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_hot_water");

                    b.Property<bool?>("HasPool")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_pool");

                    b.Property<bool?>("HasWifi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_wifi");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("image_urls");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<bool?>("PetsAllowed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pets_allowed");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("posted_at");

                    b.Property<decimal?>("PricePerMonth")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_month");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("property_type");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_text");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("scraped_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("ScrapedAt")
                        .HasDatabaseName("ix_listings_scraped_at");

                    b.HasIndex("LocationId", "PostedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_listings_location_id_posted_at");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_listings_source_id_external_id");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("RR.Core.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Areas")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("areas");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastDiscoveryAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_discovery_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SearchKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("search_keywords");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_slug");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("RR.Core.Domain.ScrapeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER")
                        .HasColumnName("consecutive_failures");

                    b.Property<bool>("IsAutoDiscovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_auto_discovered");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastScrapedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_scraped_at");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_success_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<int?>("MemberCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("RelevanceScore")
                        .HasColumnType("REAL")
                        .HasColumnName("relevance_score");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_scrape_sources");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_scrape_sources_location_id");

                    b.HasIndex("LocationId", "Url")
                        .IsUnique()
                        .HasDatabaseName("ix_scrape_sources_location_id_url");

                    b.ToTable("scrape_sources", (string)null);
                });

            modelBuilder.Entity("RR.Core.Domain.UserFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Areas")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("areas");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastMatchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_matched_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_id");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("max_price");

                    b.Property<int?>("MinBedrooms")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_bedrooms");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("min_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PropertyTypes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("property_types");

                    b.Property<bool?>("RequireHotWater")
                        .HasColumnType("INTEGER")
                        .HasColumnName("require_hot_water");

                    b.Property<bool?>("RequirePetsAllowed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("require_pets_allowed");

                    b.Property<bool?>("RequirePool")
                        .HasColumnType("INTEGER")
                        .HasColumnName("require_pool");

                    b.Property<string>("SemanticQuery")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("semantic_query");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("telegram_chat_id");

                    b.HasKey("Id")
                        .HasName("pk_user_filters");

                    b.HasIndex("TelegramChatId")
                        .HasDatabaseName("ix_user_filters_telegram_chat_id");

                    b.HasIndex("LocationId", "IsActive")
                        .HasDatabaseName("ix_user_filters_location_id_is_active");

                    b.ToTable("user_filters", (string)null);
                });

            modelBuilder.Entity("RR.Core.Domain.Listing", b =>
                {
                    b.HasOne("RR.Core.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listings_locations_location_id");

                    b.HasOne("RR.Core.Domain.ScrapeSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listings_scrape_sources_source_id");
                });

            modelBuilder.Entity("RR.Core.Domain.ScrapeSource", b =>
                {
                    b.HasOne("RR.Core.Domain.Location", null)
                        .WithMany("Sources")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scrape_sources_locations_location_id");
                });

            modelBuilder.Entity("RR.Core.Domain.UserFilter", b =>
                {
                    b.HasOne("RR.Core.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_filters_locations_location_id");
                });

            modelBuilder.Entity("RR.Core.Domain.Location", b =>
                {
                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
